#!/usr/bin/env python3
# Copyright (C) 2026 Paolo De Marinis
# SPDX-License-Identifier: GPL-3.0-or-later
"""Synthetic multi-kernel Limine reconciliation tests."""

from __future__ import annotations

import hashlib
import importlib.util
import io
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest
from contextlib import redirect_stdout
from unittest import mock


ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location(
    "kernel_entries", ROOT / "scripts/05-kernel-entries.py"
)
assert SPEC and SPEC.loader
entries = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(entries)


@unittest.skipUnless(os.name == "posix", "Linux ownership and filesystem semantics required")
class KernelEntriesTest(unittest.TestCase):
    def setUp(self):
        self.temp = Path(tempfile.mkdtemp(prefix="omen-kernel-entries-test."))
        self.esp = self.temp / "boot"
        self.state = self.temp / "state"
        self.esp.mkdir(mode=0o700)
        self.state.mkdir(mode=0o700)
        (self.state / "early.cpio").write_bytes(b"070701-omen-acpi-early")
        (self.state / "early.sha256").write_text(
            hashlib.sha256((self.state / "early.cpio").read_bytes()).hexdigest() + "\n"
        )
        self.lsinitcpio = self.temp / "lsinitcpio"
        self.lsinitcpio.write_text(
            "#!/bin/sh\nprintf '%s\\n' usr/bin/init usr/lib/modules/nvidia.ko.zst\n"
        )
        self.lsinitcpio.chmod(0o755)
        self.environment = mock.patch.dict(
            os.environ,
            {
                "OMEN_ACPI_TESTING": "1",
                "OMEN_ACPI_TEST_LSINITCPIO": str(self.lsinitcpio),
            },
            clear=False,
        )
        self.environment.start()
        self.write_stock(("linux-cachyos",))

    def tearDown(self):
        self.environment.stop()
        shutil.rmtree(self.temp)

    def payload(self, name: str, content: bytes) -> str:
        path = self.esp / "machine" / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
        return f"boot():/machine/{name}#{entries.blake2(path)}"

    def stock_block(self, kernel_id: str, *, fallback: bool = False) -> str:
        suffix = "-fallback" if fallback else ""
        entry_id = kernel_id + suffix
        kernel = self.payload(f"{kernel_id}/vmlinuz", f"kernel-{kernel_id}".encode())
        initramfs = self.payload(
            f"{kernel_id}/initramfs{suffix}", f"initramfs-{entry_id}".encode()
        )
        ucode = self.payload("cpu-ucode.img", b"microcode")
        return (
            f"//{entry_id}\n"
            "    ### This kernel entry is auto-generated by limine-entry-tool\n"
            f"    comment: Kernel version: fixture-{kernel_id}\n"
            f"    comment: kernel-id={entry_id}\n"
            "    protocol: linux\n"
            f"    module_path: {ucode}\n"
            f"    module_path: {initramfs}\n"
            f"    path: {kernel}\n"
            "    cmdline: quiet root=UUID=fixture\n"
        )

    def write_stock(
        self,
        kernel_ids: tuple[str, ...],
        *,
        fallbacks: tuple[str, ...] = (),
        extra: str = "",
    ) -> None:
        blocks = [self.stock_block(kernel_id) for kernel_id in kernel_ids]
        blocks.extend(self.stock_block(kernel_id, fallback=True) for kernel_id in fallbacks)
        config = (
            "timeout: 5\n"
            "default_entry: 1\n"
            "/CachyOS\n"
            + "".join(blocks)
            + extra
            + "//Snapshots\n"
            "///42 | historical\n"
            "////linux-cachyos\n"
            "    protocol: linux\n"
            "    path: boot():/missing-snapshot-kernel\n"
            "    module_path: boot():/missing-snapshot-initramfs\n"
            "/User rescue\n"
            "    protocol: linux\n"
            "    path: boot():/user-kernel\n"
            "    module_path: boot():/user-initramfs\n"
        )
        (self.esp / "limine.conf").write_text(config)

    def sync(self, variant: str = "s5") -> str:
        output = io.StringIO()
        with redirect_stdout(output):
            entries.sync(self.esp, self.state, variant)
        return output.getvalue()

    def managed_titles(self) -> list[str]:
        names = set(entries.variant_names("s5").values()) | set(
            entries.variant_names("combined").values()
        ) | set(entries.variant_names("s5-vfio").values())
        return [
            item["title"]
            for item in entries.parse_entries((self.esp / "limine.conf").read_text())
            if item["title"] in names and item["level"] == 2
        ]

    def test_standard_only_is_idempotent_and_preserves_stock(self):
        before_stock = self.stock_block("linux-cachyos")
        self.write_stock(("linux-cachyos",))
        self.sync()
        first = (self.esp / "limine.conf").read_bytes()
        self.sync()
        self.assertEqual((self.esp / "limine.conf").read_bytes(), first)
        self.assertEqual(self.managed_titles(), ["zz-OMEN ACPI S5"])
        self.assertIn(before_stock, first.decode())
        self.assertIn("module_path: boot():/omen-acpi/s5/early.cpio#", first.decode())
        self.assertEqual(first.decode().count("zz-OMEN ACPI S5"), 1)
        self.assertIn("default_entry: 1", first.decode())
        self.assertIn(
            "Experimental S5 GPU power-off override. Stock CachyOS entry unchanged.",
            first.decode(),
        )

    def test_lts_only_and_both_kernels_get_separate_entries(self):
        self.write_stock(("linux-cachyos-lts",), fallbacks=("linux-cachyos-lts",))
        config = self.esp / "limine.conf"
        config.write_text(
            config.read_text().replace(
                "//linux-cachyos-lts\n", "//CachyOS LTS custom label\n", 1
            )
        )
        self.sync()
        self.assertEqual(self.managed_titles(), ["zz-OMEN ACPI S5 LTS"])
        output = io.StringIO()
        with redirect_stdout(output):
            entries.status(self.esp, self.state, "s5")
        report = output.getvalue()
        self.assertIn("KERNEL\tlinux-cachyos-lts", report)
        self.assertIn("FALLBACK\tlinux-cachyos-lts\tpresent", report)
        self.assertIn("MODULE\tlinux-cachyos-lts\t1\t", report)
        self.assertIn("nvidia.ko.zst", report)

        self.write_stock(("linux-cachyos", "linux-cachyos-lts"))
        shutil.rmtree(self.esp / "omen-acpi")
        (self.state / "kernel-entries.json").unlink()
        self.sync()
        self.assertEqual(
            self.managed_titles(),
            ["zz-OMEN ACPI S5", "zz-OMEN ACPI S5 LTS"],
        )

    def test_lts_add_update_and_remove_are_reconciled_without_duplicates(self):
        self.sync()
        old = json.loads((self.state / "kernel-entries.json").read_text())
        old_standard = old["entries"]["linux-cachyos"]

        current = (self.esp / "limine.conf").read_text()
        owned_start = current.index("//zz-OMEN ACPI S5")
        owned = current[owned_start : current.index("//Snapshots")]
        self.write_stock(("linux-cachyos", "linux-cachyos-lts"), extra=owned)
        self.sync()
        self.assertEqual(len(self.managed_titles()), 2)

        current = (self.esp / "limine.conf").read_text()
        lts_initramfs = self.esp / "machine/linux-cachyos-lts/initramfs"
        old_path = next(
            value
            for value in json.loads((self.state / "kernel-entries.json").read_text())["entries"]["linux-cachyos-lts"]["module_paths"]
            if "linux-cachyos-lts/initramfs" in value
        )
        lts_initramfs.write_bytes(b"updated-lts-initramfs")
        new_path = f"boot():/machine/linux-cachyos-lts/initramfs#{entries.blake2(lts_initramfs)}"
        (self.esp / "limine.conf").write_text(current.replace(old_path, new_path, 1))
        rc = entries.status(self.esp, self.state, "s5")
        self.assertEqual(rc, 3)
        self.sync()
        updated = json.loads((self.state / "kernel-entries.json").read_text())
        self.assertIn(new_path, updated["entries"]["linux-cachyos-lts"]["module_paths"])
        self.assertEqual(updated["entries"]["linux-cachyos"], old_standard)

        current = (self.esp / "limine.conf").read_text()
        lts = next(
            item
            for item in entries.parse_entries(current)
            if item["title"] == "linux-cachyos-lts" and item["level"] == 2
        )
        lines = current.splitlines()
        del lines[lts["start"] : lts["end"]]
        (self.esp / "limine.conf").write_text("\n".join(lines) + "\n")
        self.sync()
        self.assertEqual(self.managed_titles(), ["zz-OMEN ACPI S5"])

    def test_combined_coexists_and_remove_preserves_every_stock_entry(self):
        self.write_stock(("linux-cachyos", "linux-cachyos-lts"))
        self.sync("s5")
        combined_state = self.temp / "combined"
        shutil.copytree(self.state, combined_state)
        (combined_state / "kernel-entries.json").unlink()
        entries.sync(self.esp, combined_state, "combined")
        self.assertEqual(len(self.managed_titles()), 4)
        stock_before = [
            item["title"]
            for item in entries.parse_entries((self.esp / "limine.conf").read_text())
            if item["title"] in entries.SUPPORTED
        ]
        entries.remove(self.esp, self.state, "s5")
        self.assertEqual(len(self.managed_titles()), 2)
        stock_after = [
            item["title"]
            for item in entries.parse_entries((self.esp / "limine.conf").read_text())
            if item["title"] in entries.SUPPORTED
        ]
        self.assertEqual(stock_after, stock_before)

    def test_vfio_variant_coexists_and_has_its_own_entries(self):
        self.write_stock(("linux-cachyos", "linux-cachyos-lts"))
        self.sync("s5")
        vfio_state = self.temp / "s5-vfio"
        shutil.copytree(self.state, vfio_state)
        (vfio_state / "kernel-entries.json").unlink()
        entries.sync(self.esp, vfio_state, "s5-vfio")
        self.assertEqual(
            sorted(self.managed_titles()),
            sorted([
                "zz-OMEN ACPI S5",
                "zz-OMEN ACPI S5 LTS",
                "zz-OMEN ACPI S5 VFIO",
                "zz-OMEN ACPI S5 VFIO LTS",
            ]),
        )
        text = (self.esp / "limine.conf").read_text()
        self.assertIn(
            "Experimental VFIO/Looking Glass S5 override (NVDE=1). "
            "Stock CachyOS entry unchanged.",
            text,
        )

    def test_historical_snapshot_entries_do_not_block_active_install(self):
        config = self.esp / "limine.conf"
        historical = (
            "////zz-omen-acpi-s5-test\n"
            "    comment: kernel-id=zz-omen-acpi-s5-test\n"
            "    protocol: linux\n"
            "    path: boot():/historical-kernel\n"
            "    module_path: boot():/historical-initramfs\n"
        )
        config.write_text(
            config.read_text().replace("/User rescue\n", historical + "/User rescue\n")
        )

        self.sync()

        self.assertIn(historical, config.read_text())
        self.assertEqual(entries.status(self.esp, self.state, "s5"), 0)

    def test_missing_paths_ambiguity_and_modified_owned_entry_fail_closed(self):
        config = self.esp / "limine.conf"
        before = config.read_bytes()
        (self.esp / "machine/linux-cachyos/initramfs").unlink()
        with self.assertRaises(entries.Failure):
            self.sync()
        self.assertEqual(config.read_bytes(), before)

        self.write_stock(("linux-cachyos",))
        duplicate = self.stock_block("linux-cachyos")
        config.write_text(config.read_text().replace("//Snapshots\n", duplicate + "//Snapshots\n"))
        before = config.read_bytes()
        with self.assertRaises(entries.Failure):
            self.sync()
        self.assertEqual(config.read_bytes(), before)

        self.write_stock(("linux-cachyos",))
        self.sync()
        (self.esp / "omen-acpi/s5/early.cpio").unlink()
        self.assertEqual(entries.status(self.esp, self.state, "s5"), 3)
        self.sync()
        config.write_text(config.read_text().replace("omen-acpi-owned=v1", "omen-acpi-owned=modified", 1))
        before = config.read_bytes()
        with self.assertRaises(entries.Failure):
            self.sync()
        self.assertEqual(config.read_bytes(), before)

    def test_previous_single_kernel_state_migrates_without_rebuilding_aml(self):
        scripts = self.temp / "migration-scripts"
        scripts.mkdir()
        manager = scripts / "03-manage-limine-entry.sh"
        manager.write_text(
            (ROOT / "scripts/03-manage-limine-entry.sh")
            .read_text()
            .removesuffix('main "$@"\n')
        )
        helper = scripts / "05-kernel-entries.py"
        shutil.copy2(ROOT / "scripts/05-kernel-entries.py", helper)
        helper.chmod(0o755)

        old_state = self.temp / "old-state"
        old_state.mkdir(mode=0o700)
        aml = b"synthetic validated DSDT retained across migration"
        files = {
            "variant.txt": b"s5\n",
            "expected-revision.txt": b"0x0107200A\n",
            "DSDT.aml": aml,
            "kernel.img": b"old frozen kernel",
            "initramfs.img": b"old frozen initramfs",
            "dropin.conf": b"old owned drop-in\n",
        }
        for name, content in files.items():
            (old_state / name).write_bytes(content)
        for stem, name in {
            "DSDT": "DSDT.aml",
            "kernel": "kernel.img",
            "initramfs": "initramfs.img",
            "dropin": "dropin.conf",
        }.items():
            (old_state / f"{stem}.sha256").write_text(
                hashlib.sha256((old_state / name).read_bytes()).hexdigest()
                + "\n"
            )
        dropin = self.temp / "old-dropin.conf"
        shutil.copy2(old_state / "dropin.conf", dropin)

        config = self.esp / "limine.conf"
        stock = next(
            item
            for item in entries.parse_entries(config.read_text())
            if item["title"] == "linux-cachyos"
        )
        kernel, command, modules = entries.boot_fields(stock)
        old_entry = (
            "//zz-omen-acpi-s5-test\n"
            "    protocol: linux\n"
            f"    kernel_path: {kernel}\n"
            f"    module_path: {modules[-1]}\n"
            f"    cmdline: {command}\n"
        )
        config.write_text(config.read_text().replace("//Snapshots\n", old_entry + "//Snapshots\n"))

        mock_bin = self.temp / "migration-bin"
        mock_bin.mkdir()
        shutil.copy2(self.lsinitcpio, mock_bin / "lsinitcpio")
        tool = mock_bin / "limine-entry-tool"
        tool.write_text(
            "#!/usr/bin/python3\n"
            "import os, re, sys\n"
            "path = os.environ['TEST_CONFIG']\n"
            "name = sys.argv[sys.argv.index('--remove-kernel') + 1]\n"
            "lines = open(path, encoding='utf-8').read().splitlines(keepends=True)\n"
            "start = next(i for i, line in enumerate(lines) if (match := re.match(r'^/+(.+?)\\n?$', line)) and match.group(1) == name)\n"
            "end = next((i for i in range(start + 1, len(lines)) if re.match(r'^/+', lines[i])), len(lines))\n"
            "open(path, 'w', encoding='utf-8').writelines(lines[:start] + lines[end:])\n"
        )
        tool.chmod(0o755)
        cpio = mock_bin / "cpio"
        cpio.write_text("#!/bin/sh\ncat\n")
        cpio.chmod(0o755)

        environment = dict(os.environ)
        environment.update(
            OMEN_ACPI_TESTING="1",
            OMEN_ACPI_TEST_LSINITCPIO=str(self.lsinitcpio),
            TEST_CONFIG=str(config),
            TEST_ESP=str(self.esp),
            TEST_STATE=str(old_state),
            TEST_DROPIN=str(dropin),
            TEST_BIN=str(mock_bin),
            TEST_TEMP=str(self.temp),
        )
        script = r'''
source "$1"
select_variant s5
STATE_DIR="$TEST_STATE"
DROPIN="$TEST_DROPIN"
require_root() { :; }
acquire_lock() { :; }
find_esp() { printf '%s\n' "$TEST_ESP"; }
read_machine() { MACHINE_PRODUCT=fixture; MACHINE_BOARD=fixture; MACHINE_BIOS=fixture; }
machine_is_reference() { return 0; }
install() {
    local -a filtered=()
    while (($#)); do
        case "$1" in -o|-g) shift 2 ;; *) filtered+=("$1"); shift ;; esac
    done
    /usr/bin/install "${filtered[@]}"
}
mktemp() {
    if [[ "${*: -1}" == /var/tmp/omen-acpi-override.* ]]; then
        /usr/bin/mktemp -d "$TEST_TEMP/migration-work.XXXXXX"
    else
        /usr/bin/mktemp "$@"
    fi
}
safe_remove_temp_dir() { [[ -z "${1:-}" ]] || /usr/bin/rm -rf -- "$1"; }
export PATH="$TEST_BIN:/usr/bin:/bin"
refresh_action
'''
        result = subprocess.run(
            ["bash", "-c", script, "_", str(manager)],
            text=True,
            capture_output=True,
            env=environment,
            check=False,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual((old_state / "DSDT.aml").read_bytes(), aml)
        self.assertTrue((old_state / "kernel-entries.json").is_file())
        self.assertFalse(dropin.exists())
        self.assertFalse((old_state / "kernel.img").exists())
        self.assertEqual(self.managed_titles(), ["zz-OMEN ACPI S5"])

    def test_legacy_titles_are_migrated_and_globals_stay_put(self):
        self.sync()
        current = (self.esp / "limine.conf").read_text()
        migrated = current.replace("zz-OMEN ACPI S5", "zz-omen-acpi-s5-test")
        (self.esp / "limine.conf").write_text(migrated)
        manifest = json.loads((self.state / "kernel-entries.json").read_text())
        manifest["entries"]["linux-cachyos"]["title"] = "zz-omen-acpi-s5-test"
        (self.state / "kernel-entries.json").write_text(json.dumps(manifest, indent=2) + "\n")
        self.assertEqual(entries.status(self.esp, self.state, "s5"), 3)
        self.sync()
        updated = (self.esp / "limine.conf").read_text()
        self.assertEqual(self.managed_titles(), ["zz-OMEN ACPI S5"])
        self.assertNotIn("//zz-omen-acpi-s5-test\n", updated)
        self.assertIn("default_entry: 1", updated)
        self.assertEqual(
            entries.limine_globals(current),
            entries.limine_globals(updated),
        )
        self.assertEqual(
            entries.supported_stock_fingerprint(current),
            entries.supported_stock_fingerprint(updated),
        )

    def test_stock_preservation_rejects_default_entry_edits(self):
        original = (self.esp / "limine.conf").read_text()
        tampered = original.replace("default_entry: 1", "default_entry: 2", 1)
        with self.assertRaises(entries.Failure):
            entries.assert_stock_preserved(original, tampered)

    def test_missing_entries_are_stale_and_reconstructed(self):
        self.write_stock(("linux-cachyos", "linux-cachyos-lts"))
        self.sync()
        config = self.esp / "limine.conf"
        original = config.read_text()
        manifest = entries.load_manifest(self.state, "s5")
        primary, _ = entries.supported_entries(original)
        first = next(iter(primary.values()))
        owned = entries.verify_owned_entries(original, manifest, "s5", (first["level"], first["parent"]))
        lines = original.splitlines(keepends=True)
        block = owned[0]
        config.write_text("".join(lines[:block["start"]] + lines[block["end"]:]))
        self.assertEqual(entries.status(self.esp, self.state, "s5"), 3)
        self.sync()
        self.assertEqual(entries.status(self.esp, self.state, "s5"), 0)
        self.assertEqual(len(self.managed_titles()), 2)
        # A generator can remove every custom entry while retaining stock ones.
        self.write_stock(("linux-cachyos", "linux-cachyos-lts"))
        self.assertEqual(entries.status(self.esp, self.state, "s5"), 3)
        self.sync()
        self.assertEqual(entries.status(self.esp, self.state, "s5"), 0)

    def test_current_refresh_does_not_write(self):
        self.sync()
        with mock.patch.object(entries, "write_atomic", side_effect=AssertionError("unnecessary write")):
            self.sync()

    def test_missing_entries_and_payload_can_be_removed_without_recreation(self):
        self.sync()
        self.write_stock(("linux-cachyos",))
        (self.esp / "omen-acpi/s5/early.cpio").unlink()
        entries.remove(self.esp, self.state, "s5")
        self.assertEqual(self.managed_titles(), [])
        self.assertFalse((self.esp / "omen-acpi/s5").exists())

    def test_renamed_owned_entry_is_not_recreated(self):
        self.sync()
        config = self.esp / "limine.conf"
        config.write_text(config.read_text().replace("zz-OMEN ACPI S5", "Renamed override"))
        before = config.read_bytes()
        with self.assertRaises(entries.Failure):
            self.sync()
        self.assertEqual(config.read_bytes(), before)

    def test_modified_survivor_blocks_missing_entry_repair(self):
        self.write_stock(("linux-cachyos", "linux-cachyos-lts"))
        self.sync()
        config = self.esp / "limine.conf"
        text = config.read_text()
        parsed = entries.parse_entries(text)
        missing = next(item for item in parsed if item["title"] == "zz-OMEN ACPI S5 LTS")
        lines = text.splitlines(keepends=True)
        config.write_text("".join(lines[:missing["start"]] + lines[missing["end"]:]).replace("omen-acpi-owned=v1", "omen-acpi-owned=modified", 1))
        before = config.read_bytes()
        with self.assertRaises(entries.Failure):
            self.sync()
        self.assertEqual(config.read_bytes(), before)

    def test_manifest_commit_failure_restores_config_and_missing_payload(self):
        self.sync()
        self.write_stock(("linux-cachyos", "linux-cachyos-lts"))
        target = self.esp / "omen-acpi/s5/early.cpio"
        target.unlink()
        config = self.esp / "limine.conf"
        manifest = self.state / "kernel-entries.json"
        before_config, before_manifest = config.read_bytes(), manifest.read_bytes()
        original_write = entries.write_atomic
        failed = False
        def fail_once(path, content, mode):
            nonlocal failed
            if path == manifest and not failed:
                failed = True
                raise OSError("injected manifest failure")
            original_write(path, content, mode)
        with mock.patch.object(entries, "write_atomic", side_effect=fail_once):
            with self.assertRaises(OSError):
                self.sync()
        self.assertEqual(config.read_bytes(), before_config)
        self.assertEqual(manifest.read_bytes(), before_manifest)
        self.assertFalse(target.exists())

    def test_stock_preservation_checks_raw_body_bytes(self):
        original = (self.esp / "limine.conf").read_text()
        tampered = original.replace("    protocol: linux", "  protocol: linux", 1)
        with self.assertRaises(entries.Failure):
            entries.assert_stock_preserved(original, tampered)


class EntryRulesTest(unittest.TestCase):
    """Portable checks of entry identity and preservation, without filesystem mocks."""

    def setUp(self):
        self.stock = (
            "timeout: 5\ndefault_entry: 2\n/+CachyOS\n//linux-cachyos\n"
            "    comment: kernel-id=linux-cachyos\n    protocol: linux\n"
            "    kernel_path: boot():/stock/vmlinuz\n"
            "    module_path: boot():/stock/initramfs\n    cmdline: quiet root=UUID=test\n"
        )
        source = {"kernel_id": "linux-cachyos", "title": "linux-cachyos", "level": 2,
                  "kernel_path": "boot():/stock/vmlinuz", "command": "quiet root=UUID=test",
                  "module_data": [(None, "boot():/stock/ucode", []), (None, "boot():/stock/initramfs", [])]}
        self.record = entries.entry_record("s5", source, "boot():/omen-acpi/s5/early.cpio#" + "a" * 128)
        self.block = "\n".join(entries.render_entry(self.record)) + "\n"
        self.manifest = {"entries": {"linux-cachyos": self.record}}

    def test_verified_absence_is_recoverable_but_strict_validation_still_rejects_it(self):
        with self.assertRaises(entries.Failure):
            entries.verify_owned_entries(self.stock, self.manifest, "s5", (2, 0))
        self.assertEqual(entries.verify_owned_entries(self.stock, self.manifest, "s5", (2, 0), allow_missing=True), [])

    def test_modified_or_renamed_survivors_block_reconstruction(self):
        for changed in (self.block.replace("zz-OMEN ACPI S5", "Renamed override"),
                        self.block.replace("root=UUID=test", "root=UUID=other"),
                        self.block.replace("omen-acpi-owned=v1", "omen-acpi-owned=modified")):
            with self.subTest(changed=changed):
                with self.assertRaises(entries.Failure):
                    entries.verify_owned_entries(self.stock + changed, self.manifest, "s5", (2, 0), allow_missing=True)

    def test_duplicate_survivors_block_reconstruction(self):
        with self.assertRaises(entries.Failure):
            entries.verify_owned_entries(self.stock + self.block * 2, self.manifest, "s5", (2, 0), allow_missing=True)

    def test_historical_snapshot_entries_are_preserved(self):
        historical = "//Snapshots\n" + self.block.replace("//zz-", "///zz-")
        text = self.stock + historical
        owned = entries.verify_owned_entries(text, self.manifest, "s5", (2, 0), allow_missing=True)
        updated = entries.rebuild_config(text, owned, self.manifest["entries"])
        self.assertIn(historical, updated)
        entries.assert_stock_preserved(text, updated)

    def test_early_cpio_precedes_microcode_and_initramfs(self):
        self.assertEqual(self.record["module_paths"][1:], ["boot():/stock/ucode", "boot():/stock/initramfs"])
        self.assertTrue(self.record["module_paths"][0].startswith("boot():/omen-acpi/s5/early.cpio#"))

    def test_stock_raw_bytes_and_global_default_are_protected(self):
        for changed in (self.stock.replace("    protocol", "  protocol"),
                        self.stock.replace("default_entry: 2", "default_entry: 3")):
            with self.assertRaises(entries.Failure):
                entries.assert_stock_preserved(self.stock, changed)


if __name__ == "__main__":
    unittest.main(verbosity=2)
