#!/usr/bin/env python3
# Copyright (C) 2026 Paolo De Marinis
# SPDX-License-Identifier: GPL-3.0-or-later
"""Synthetic multi-kernel Limine reconciliation tests."""

from __future__ import annotations

import hashlib
import importlib.util
import io
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest
from contextlib import redirect_stdout
from unittest import mock


ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location(
    "kernel_entries", ROOT / "scripts/05-kernel-entries.py"
)
assert SPEC and SPEC.loader
entries = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(entries)


class KernelEntriesTest(unittest.TestCase):
    def setUp(self):
        self.temp = Path(tempfile.mkdtemp(prefix="omen-kernel-entries-test."))
        self.esp = self.temp / "boot"
        self.state = self.temp / "state"
        self.esp.mkdir(mode=0o700)
        self.state.mkdir(mode=0o700)
        (self.state / "early.cpio").write_bytes(b"070701-omen-acpi-early")
        (self.state / "early.sha256").write_text(
            hashlib.sha256((self.state / "early.cpio").read_bytes()).hexdigest() + "\n"
        )
        self.lsinitcpio = self.temp / "lsinitcpio"
        self.lsinitcpio.write_text(
            "#!/bin/sh\nprintf '%s\\n' usr/bin/init usr/lib/modules/nvidia.ko.zst\n"
        )
        self.lsinitcpio.chmod(0o755)
        self.environment = mock.patch.dict(
            os.environ,
            {
                "OMEN_ACPI_TESTING": "1",
                "OMEN_ACPI_TEST_LSINITCPIO": str(self.lsinitcpio),
            },
            clear=False,
        )
        self.environment.start()
        self.write_stock(("linux-cachyos",))

    def tearDown(self):
        self.environment.stop()
        shutil.rmtree(self.temp)

    def payload(self, name: str, content: bytes) -> str:
        path = self.esp / "machine" / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
        return f"boot():/machine/{name}#{entries.blake2(path)}"

    def stock_block(self, kernel_id: str, *, fallback: bool = False) -> str:
        suffix = "-fallback" if fallback else ""
        entry_id = kernel_id + suffix
        kernel = self.payload(f"{kernel_id}/vmlinuz", f"kernel-{kernel_id}".encode())
        initramfs = self.payload(
            f"{kernel_id}/initramfs{suffix}", f"initramfs-{entry_id}".encode()
        )
        ucode = self.payload("cpu-ucode.img", b"microcode")
        return (
            f"//{entry_id}\n"
            "    ### This kernel entry is auto-generated by limine-entry-tool\n"
            f"    comment: Kernel version: fixture-{kernel_id}\n"
            f"    comment: kernel-id={entry_id}\n"
            "    protocol: linux\n"
            f"    module_path: {ucode}\n"
            f"    module_path: {initramfs}\n"
            f"    path: {kernel}\n"
            "    cmdline: quiet root=UUID=fixture\n"
        )

    def write_stock(
        self,
        kernel_ids: tuple[str, ...],
        *,
        fallbacks: tuple[str, ...] = (),
        extra: str = "",
    ) -> None:
        blocks = [self.stock_block(kernel_id) for kernel_id in kernel_ids]
        blocks.extend(self.stock_block(kernel_id, fallback=True) for kernel_id in fallbacks)
        config = (
            "timeout: 5\n"
            "default_entry: 1\n"
            "/CachyOS\n"
            + "".join(blocks)
            + extra
            + "//Snapshots\n"
            "///42 | historical\n"
            "////linux-cachyos\n"
            "    protocol: linux\n"
            "    path: boot():/missing-snapshot-kernel\n"
            "    module_path: boot():/missing-snapshot-initramfs\n"
            "/User rescue\n"
            "    protocol: linux\n"
            "    path: boot():/user-kernel\n"
            "    module_path: boot():/user-initramfs\n"
        )
        (self.esp / "limine.conf").write_text(config)

    def sync(self, variant: str = "s5") -> str:
        output = io.StringIO()
        with redirect_stdout(output):
            entries.sync(self.esp, self.state, variant)
        return output.getvalue()

    def managed_titles(self) -> list[str]:
        names = set(entries.variant_names("s5").values()) | set(
            entries.variant_names("combined").values()
        )
        return [
            item["title"]
            for item in entries.parse_entries((self.esp / "limine.conf").read_text())
            if item["title"] in names and item["level"] == 2
        ]

    def test_standard_only_is_idempotent_and_preserves_stock(self):
        before_stock = self.stock_block("linux-cachyos")
        self.write_stock(("linux-cachyos",))
        self.sync()
        first = (self.esp / "limine.conf").read_bytes()
        self.sync()
        self.assertEqual((self.esp / "limine.conf").read_bytes(), first)
        self.assertEqual(self.managed_titles(), ["zz-omen-acpi-s5-test"])
        self.assertIn(before_stock, first.decode())
        self.assertIn("module_path: boot():/omen-acpi/s5/early.cpio#", first.decode())
        self.assertEqual(first.decode().count("zz-omen-acpi-s5-test"), 1)

    def test_lts_only_and_both_kernels_get_separate_entries(self):
        self.write_stock(("linux-cachyos-lts",), fallbacks=("linux-cachyos-lts",))
        config = self.esp / "limine.conf"
        config.write_text(
            config.read_text().replace(
                "//linux-cachyos-lts\n", "//CachyOS LTS custom label\n", 1
            )
        )
        self.sync()
        self.assertEqual(self.managed_titles(), ["zz-omen-acpi-s5-test-lts"])
        output = io.StringIO()
        with redirect_stdout(output):
            entries.status(self.esp, self.state, "s5")
        report = output.getvalue()
        self.assertIn("KERNEL\tlinux-cachyos-lts", report)
        self.assertIn("FALLBACK\tlinux-cachyos-lts\tpresent", report)
        self.assertIn("MODULE\tlinux-cachyos-lts\t1\t", report)
        self.assertIn("nvidia.ko.zst", report)

        self.write_stock(("linux-cachyos", "linux-cachyos-lts"))
        shutil.rmtree(self.esp / "omen-acpi")
        (self.state / "kernel-entries.json").unlink()
        self.sync()
        self.assertEqual(
            self.managed_titles(),
            ["zz-omen-acpi-s5-test", "zz-omen-acpi-s5-test-lts"],
        )

    def test_lts_add_update_and_remove_are_reconciled_without_duplicates(self):
        self.sync()
        old = json.loads((self.state / "kernel-entries.json").read_text())
        old_standard = old["entries"]["linux-cachyos"]

        current = (self.esp / "limine.conf").read_text()
        owned_start = current.index("//zz-omen-acpi-s5-test")
        owned = current[owned_start : current.index("//Snapshots")]
        self.write_stock(("linux-cachyos", "linux-cachyos-lts"), extra=owned)
        self.sync()
        self.assertEqual(len(self.managed_titles()), 2)

        current = (self.esp / "limine.conf").read_text()
        lts_initramfs = self.esp / "machine/linux-cachyos-lts/initramfs"
        old_path = next(
            value
            for value in json.loads((self.state / "kernel-entries.json").read_text())["entries"]["linux-cachyos-lts"]["module_paths"]
            if "linux-cachyos-lts/initramfs" in value
        )
        lts_initramfs.write_bytes(b"updated-lts-initramfs")
        new_path = f"boot():/machine/linux-cachyos-lts/initramfs#{entries.blake2(lts_initramfs)}"
        (self.esp / "limine.conf").write_text(current.replace(old_path, new_path, 1))
        rc = entries.status(self.esp, self.state, "s5")
        self.assertEqual(rc, 3)
        self.sync()
        updated = json.loads((self.state / "kernel-entries.json").read_text())
        self.assertIn(new_path, updated["entries"]["linux-cachyos-lts"]["module_paths"])
        self.assertEqual(updated["entries"]["linux-cachyos"], old_standard)

        current = (self.esp / "limine.conf").read_text()
        lts = next(
            item
            for item in entries.parse_entries(current)
            if item["title"] == "linux-cachyos-lts" and item["level"] == 2
        )
        lines = current.splitlines()
        del lines[lts["start"] : lts["end"]]
        (self.esp / "limine.conf").write_text("\n".join(lines) + "\n")
        self.sync()
        self.assertEqual(self.managed_titles(), ["zz-omen-acpi-s5-test"])

    def test_combined_coexists_and_remove_preserves_every_stock_entry(self):
        self.write_stock(("linux-cachyos", "linux-cachyos-lts"))
        self.sync("s5")
        combined_state = self.temp / "combined"
        shutil.copytree(self.state, combined_state)
        (combined_state / "kernel-entries.json").unlink()
        entries.sync(self.esp, combined_state, "combined")
        self.assertEqual(len(self.managed_titles()), 4)
        stock_before = [
            item["title"]
            for item in entries.parse_entries((self.esp / "limine.conf").read_text())
            if item["title"] in entries.SUPPORTED
        ]
        entries.remove(self.esp, self.state, "s5")
        self.assertEqual(len(self.managed_titles()), 2)
        stock_after = [
            item["title"]
            for item in entries.parse_entries((self.esp / "limine.conf").read_text())
            if item["title"] in entries.SUPPORTED
        ]
        self.assertEqual(stock_after, stock_before)

    def test_historical_snapshot_entries_do_not_block_active_install(self):
        config = self.esp / "limine.conf"
        historical = (
            "////zz-omen-acpi-s5-test\n"
            "    comment: kernel-id=zz-omen-acpi-s5-test\n"
            "    protocol: linux\n"
            "    path: boot():/historical-kernel\n"
            "    module_path: boot():/historical-initramfs\n"
        )
        config.write_text(
            config.read_text().replace("/User rescue\n", historical + "/User rescue\n")
        )

        self.sync()

        self.assertIn(historical, config.read_text())
        self.assertEqual(entries.status(self.esp, self.state, "s5"), 0)

    def test_missing_paths_ambiguity_and_modified_owned_entry_fail_closed(self):
        config = self.esp / "limine.conf"
        before = config.read_bytes()
        (self.esp / "machine/linux-cachyos/initramfs").unlink()
        with self.assertRaises(entries.Failure):
            self.sync()
        self.assertEqual(config.read_bytes(), before)

        self.write_stock(("linux-cachyos",))
        duplicate = self.stock_block("linux-cachyos")
        config.write_text(config.read_text().replace("//Snapshots\n", duplicate + "//Snapshots\n"))
        before = config.read_bytes()
        with self.assertRaises(entries.Failure):
            self.sync()
        self.assertEqual(config.read_bytes(), before)

        self.write_stock(("linux-cachyos",))
        self.sync()
        (self.esp / "omen-acpi/s5/early.cpio").unlink()
        self.assertEqual(entries.status(self.esp, self.state, "s5"), 3)
        self.sync()
        config.write_text(config.read_text().replace("omen-acpi-owned=v1", "omen-acpi-owned=modified", 1))
        before = config.read_bytes()
        with self.assertRaises(entries.Failure):
            self.sync()
        self.assertEqual(config.read_bytes(), before)

    def test_previous_single_kernel_state_migrates_without_rebuilding_aml(self):
        scripts = self.temp / "migration-scripts"
        scripts.mkdir()
        manager = scripts / "03-manage-limine-entry.sh"
        manager.write_text(
            (ROOT / "scripts/03-manage-limine-entry.sh")
            .read_text()
            .removesuffix('main "$@"\n')
        )
        helper = scripts / "05-kernel-entries.py"
        shutil.copy2(ROOT / "scripts/05-kernel-entries.py", helper)
        helper.chmod(0o755)

        old_state = self.temp / "old-state"
        old_state.mkdir(mode=0o700)
        aml = b"synthetic validated DSDT retained across migration"
        files = {
            "variant.txt": b"s5\n",
            "expected-revision.txt": b"0x0107200A\n",
            "DSDT.aml": aml,
            "kernel.img": b"old frozen kernel",
            "initramfs.img": b"old frozen initramfs",
            "dropin.conf": b"old owned drop-in\n",
        }
        for name, content in files.items():
            (old_state / name).write_bytes(content)
        for stem, name in {
            "DSDT": "DSDT.aml",
            "kernel": "kernel.img",
            "initramfs": "initramfs.img",
            "dropin": "dropin.conf",
        }.items():
            (old_state / f"{stem}.sha256").write_text(
                hashlib.sha256((old_state / name).read_bytes()).hexdigest()
                + "\n"
            )
        dropin = self.temp / "old-dropin.conf"
        shutil.copy2(old_state / "dropin.conf", dropin)

        config = self.esp / "limine.conf"
        stock = next(
            item
            for item in entries.parse_entries(config.read_text())
            if item["title"] == "linux-cachyos"
        )
        kernel, command, modules = entries.boot_fields(stock)
        old_entry = (
            "//zz-omen-acpi-s5-test\n"
            "    protocol: linux\n"
            f"    kernel_path: {kernel}\n"
            f"    module_path: {modules[-1]}\n"
            f"    cmdline: {command}\n"
        )
        config.write_text(config.read_text().replace("//Snapshots\n", old_entry + "//Snapshots\n"))

        mock_bin = self.temp / "migration-bin"
        mock_bin.mkdir()
        shutil.copy2(self.lsinitcpio, mock_bin / "lsinitcpio")
        tool = mock_bin / "limine-entry-tool"
        tool.write_text(
            "#!/usr/bin/python3\n"
            "import os, re, sys\n"
            "path = os.environ['TEST_CONFIG']\n"
            "name = sys.argv[sys.argv.index('--remove-kernel') + 1]\n"
            "lines = open(path, encoding='utf-8').read().splitlines(keepends=True)\n"
            "start = next(i for i, line in enumerate(lines) if (match := re.match(r'^/+(.+?)\\n?$', line)) and match.group(1) == name)\n"
            "end = next((i for i in range(start + 1, len(lines)) if re.match(r'^/+', lines[i])), len(lines))\n"
            "open(path, 'w', encoding='utf-8').writelines(lines[:start] + lines[end:])\n"
        )
        tool.chmod(0o755)

        environment = dict(os.environ)
        environment.update(
            OMEN_ACPI_TESTING="1",
            OMEN_ACPI_TEST_LSINITCPIO=str(self.lsinitcpio),
            TEST_CONFIG=str(config),
            TEST_ESP=str(self.esp),
            TEST_STATE=str(old_state),
            TEST_DROPIN=str(dropin),
            TEST_BIN=str(mock_bin),
            TEST_TEMP=str(self.temp),
        )
        script = r'''
source "$1"
select_variant s5
STATE_DIR="$TEST_STATE"
DROPIN="$TEST_DROPIN"
require_root() { :; }
acquire_lock() { :; }
find_esp() { printf '%s\n' "$TEST_ESP"; }
read_machine() { MACHINE_PRODUCT=fixture; MACHINE_BOARD=fixture; MACHINE_BIOS=fixture; }
machine_is_reference() { return 0; }
install() {
    local -a filtered=()
    while (($#)); do
        case "$1" in -o|-g) shift 2 ;; *) filtered+=("$1"); shift ;; esac
    done
    /usr/bin/install "${filtered[@]}"
}
mktemp() {
    if [[ "${*: -1}" == /var/tmp/omen-acpi-override.* ]]; then
        /usr/bin/mktemp -d "$TEST_TEMP/migration-work.XXXXXX"
    else
        /usr/bin/mktemp "$@"
    fi
}
safe_remove_temp_dir() { [[ -z "${1:-}" ]] || /usr/bin/rm -rf -- "$1"; }
export PATH="$TEST_BIN:/usr/bin:/bin"
refresh_action
'''
        result = subprocess.run(
            ["bash", "-c", script, "_", str(manager)],
            text=True,
            capture_output=True,
            env=environment,
            check=False,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual((old_state / "DSDT.aml").read_bytes(), aml)
        self.assertTrue((old_state / "kernel-entries.json").is_file())
        self.assertFalse(dropin.exists())
        self.assertFalse((old_state / "kernel.img").exists())
        self.assertEqual(self.managed_titles(), ["zz-omen-acpi-s5-test"])


if __name__ == "__main__":
    unittest.main(verbosity=2)
